### ISSUE TITLE
The https://blockchain.info/balance is rate limited

### ISSUE THREAD

**Issue by BalancerK** [HugoXOX3/CryptoWalletMiner#1]

**Comment by BalancerK** [comment]
https://blockchain.info/balance is rate limited, so after running some times the code shows 429 Client Error: Too Many Requests for url

**Comment by HugoXOX3** [comment]
Try to only run one CryptoWalletMiner at the same time because the blockchain.info can't response that much requests

**Comment by HugoXOX3** [comment]
If this still does't work,try this(but the speed will become slower than before):
Add ```import time``` at the beginning and ```time.sleep(1)``` at the end
* Try to adjust the sleep time to get better performance
